### ISSUE TITLE
DAZN Kanäle laufen bei pvr,plutotv nicht

### ISSUE THREAD

**Issue by LeimertPark** [kodi-pvr/pvr.plutotv#59]
Seit einigen Wochen laufen die DAZN Sender von Pluto im pvr.pluto nicht mehr.Im Kodi kommt der Hinweis:
Allgemeiner Wiedergabefehler.Bitte im Protokoll nachschauen!Benutzte Nexus 20
Aber auch im auf meinem Omega am PC gibt Kodi diesselbe Meldung!

Könntest du mal nachschauen?

Vielen Dank!

The DAZN channels from Pluto have not been running in pvr.pluto for a few weeks now. The message appears in the Kodi:
General playback error. Please check the log! Used Nexus 20
But Kodi also gives the same message on my Omega on the PC!

Could you take a look?

Thank you!

**Comment by LeimertPark** [comment]
Das Problem besteht weiterhin!

**Comment by ksooo** [comment]
Nothing that can be fixed in the add-on, sorry. Most probably an inputstream.adaptive issue.
