### ISSUE TITLE
Commercials crash constantly 

### ISSUE THREAD

**Issue by Schmell** [kodi-pvr/pvr.plutotv#85]
Some Stack tv commercials (but not all) in particular are always freezing up and sometimes that will crash the program. Its weird because it will tear or pause in the same spot fequently.
And sometimes it will just crash the video and the player thinks it is playing audio.

I a running Kodi v21.1
Nvidia Sheild

**Comment by ksooo** [comment]
This (if at all) can only be solved in the inputstream.adaptive add-on, which is used by pvr.plutotv for all playback. The dev knows about this problems, but there is no 100% solution, as far as I know.
