### ISSUE TITLE
Create channel group for "Pluto TV"

### ISSUE THREAD

**Issue by Chris230291** [kodi-pvr/pvr.plutotv#89]
Hello, thanks for making this.
Could we have an option to create a channel group for all the channels called “Pluto TV”?
Perhaps have an additional option to create category groups… I wouldn't use this one, but others might like it?
The reason I ask is that I use TVHeadend with channel groups for different sources, and the Pluto channels just get put in the “All Channels” group.

**Comment by ksooo** [comment]
> Could we have an option to create a channel group for all the channels called “Pluto TV”?

This is already available in the Kodi v22 nightly builds.
